apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-sdta
  region: us-west-1

nodeGroups:
  - name: nodegrp
    labels: { role: workers }
    instanceType: t4g.xlarge
    desiredCapacity: 1
    volumeSize: 20
    privateNetworking: true
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
      enableSsm: true
    iam:
      withAddonPolicies:
        imageBuilder: true
